[workspace]
edition = "2021"
members = ["embassy-keypad", "pcd8544"]

[package]
edition = "2021"
name = "embassy-rp-examples"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]
embassy-keypad = { path = "./embassy-keypad" }
embedded-hal-1 = { package = "embedded-hal", version = "1.0" }
embassy-embedded-hal = { version = "0.2.0", path = "/home/tom/embassy/embassy-embedded-hal", features = ["defmt"] }
embassy-sync = { version = "0.6.0", path = "/home/tom/embassy/embassy-sync", features = ["defmt"] }
embassy-executor = { version = "0.6.0", path = "/home/tom/embassy/embassy-executor", features = ["task-arena-size-98304", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"] }
embassy-time = { version = "0.3.2", path = "/home/tom/embassy/embassy-time", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-rp = { version = "0.2.0", path = "/home/tom/embassy/embassy-rp", features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl", "rp2040"] }
embassy-usb = { version = "0.3.0", path = "/home/tom/embassy/embassy-usb", features = ["defmt"] }
embassy-futures = { version = "0.1.0", path = "/home/tom/embassy/embassy-futures" }
embassy-usb-logger = { version = "0.2.0", path = "/home/tom/embassy/embassy-usb-logger" }

defmt = "0.3"
defmt-rtt = "0.4"
fixed = "1.23.1"
fixed-macro = "1.2"

cortex-m = { version = "0.7.6", features = ["inline-asm"] }
cortex-m-rt = "0.7.0"
critical-section = "1.1"
panic-probe = { version = "0.3", features = ["print-defmt"] }
usbd-hid = "0.8.1"
embedded-graphics = "0.8.1"
pcd8544 = { path = "./pcd8544" }
display-interface-spi = "0.5.0"

[profile.release]
debug = 2
lto = true
opt-level = 'z'

[profile.dev]
debug = 2
lto = true
opt-level = "z"

[patch.crates-io]
embassy-executor = { path = "/home/tom/embassy/embassy-executor" }
embassy-sync = { path = "/home/tom/embassy/embassy-sync" }
embassy-futures = { path = "/home/tom/embassy/embassy-futures" }
embassy-time = { path = "/home/tom/embassy/embassy-time" }
embassy-time-driver = { path = "/home/tom/embassy/embassy-time-driver" }
embassy-embedded-hal = { path = "/home/tom/embassy/embassy-embedded-hal" }
