[package]
name = "pcd8544"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-graphics-core = "0.4.0"
display-interface = "0.5.0"
embedded-hal = "1.0.0"

[dev-dependencies]
embedded-hal-mock = "0.11.1"
