[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-graphics = { workspace = true }
fastrand = { version = "2.1.1", default-features = false }
multi-tap = { workspace = true }
embassy-futures = { workspace = true }
embassy-time = { workspace = true }
