[package]
name = "hardware-test"
version = "0.1.0"
edition = "2024"

[dependencies]
defmt.workspace = true
embassy-time = { workspace = true }
embedded-graphics = "0.8"
embedded-text = "0.7.2"
enum-iterator = "2.1.0"
shared = { path = "../shared" }
usbd-hid = "*"
