[package]
name = "hardware-test"
version = "0.1.0"
edition = "2024"

[dependencies]
defmt.workspace = true
embassy-time = { workspace = true }
embedded-graphics = "0.8"
shared = { path = "../shared" }
