[package]
name = "clock"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.39", default-features = false }
embassy-time = { workspace = true }
embedded-graphics = "0.8"
heapless = "0.8.0"
shared = { path = "../shared" }
