[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-time = { workspace = true }
embedded-graphics = "0.8"
embedded-graphics-core = "0.4.0"
embedded-text = "0.7.2"
enum-iterator = "2.1.0"
enum-iterator-derive = "1.4.0"
log = "0.4"
strum = { version = "0.27.1", features = ["derive"], default-features = false }
strum_macros = "0.27.1"
