[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.39", default-features = false, optional = true }
embassy-time = { workspace = true }
embedded-graphics = "0.8"
