name: KiCAD

defaults:
  run:
    working-directory: ./kicad

on:
  push:
  schedule:
    - cron: '43 5 * * 3'

permissions:
  contents: write

jobs:
  ERC:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto:latest

    steps:
    - uses: actions/checkout@v4

    - name: Run ERC
      run: |
        kibot  -d jlcpcb -s drc -i -e brique.kicad_sch

  DRC:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto:latest
    needs: ERC

    steps:
    - uses: actions/checkout@v4

    - name: Run DRC
      run: |
        [ -f *.kicad_pcb ] && kibot  -d jlcpcb -s erc -i -e brique.kicad_sch

  JLCPCB:
    name: JLCPCB Files
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto_full:latest
    needs: DRC
  
    steps:
    - uses: actions/checkout@v4
  
    - name: Generate files
      run: |
        [ -f *.kicad_pcb ] && kibot  -d jlcpcb -e brique.kicad_sch -s all bom gerbers gerb_drill position blender_export pdf_sch_print pcb_print

    - name: Upload Files
      uses: actions/upload-artifact@v4
      with:
        name: JLCPCB
        path: kicad/jlcpcb
        if-no-files-found: error

    - uses: vimtor/action-zip@v1.2
      with:
        files: kicad/jlcpcb/gerber
        dest: gerbers.zip

    - name: Run FCBot
      uses: asymworks/fcbot@v0
      with:
        dir: output
        config: connection_plate/fcbot.yaml
        project: connection_plate/hollow.FCStd

    - name: ls
      run: ls ..

    - name: ls connection_plate
      run: ls ../connection_plate
  
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          kicad/jlcpcb/bom.csv
          kicad/jlcpcb/cpl.csv
          kicad/jlcpcb/schematic.pdf
          kicad/jlcpcb/pcb.svg
          kicad/jlcpcb/3D_blenderback.png
          kicad/jlcpcb/3D_blenderfront.png
          gerbers.zip
          part.stl
          part.png
        fail_on_unmatched_files: true
        # draft: true
