name: KiCAD

defaults:
  run:
    working-directory: ./kicad

on:
  push:
  schedule:
    - cron: '43 5 * * 3'

permissions:
  contents: write

jobs:
  ERC:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto:latest

    steps:
    - uses: actions/checkout@v4

    - name: Run ERC
      run: |
        kibot  -d jlcpcb -s drc -i -e brique.kicad_sch

  DRC:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto:latest
    needs: ERC

    steps:
    - uses: actions/checkout@v4

    - name: Run DRC
      run: |
        [ -f *.kicad_pcb ] && kibot  -d jlcpcb -s erc -i -e brique.kicad_sch

  JLCPCB:
    name: JLCPCB Files
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto_full:latest
    needs: DRC
  
    steps:
    - uses: actions/checkout@v4
  
    - name: Generate files
      run: |
        [ -f *.kicad_pcb ] && kibot  -d jlcpcb -e brique.kicad_sch -s all bom gerbers gerb_drill position
    
    - name: Upload Files
      uses: actions/upload-artifact@v4
      with:
        name: JLCPCB
        path: kicad/jlcpcb
        if-no-files-found: error

    - uses: vimtor/action-zip@v1.2
      with:
        files: kicad/jlcpcb
        dest: gerbers.zip
  
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          kicad/jlcpcb/bom.csv
          kicad/jlcpcb/cpl.csv
          gerbers.zip
        fail_on_unmatched_files: true
        # draft: true
