name: Page

on:
  push:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  Page:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: rust-docs
        targets: thumbv8m.main-none-eabihf
    - run: cargo install --locked trunk
    - run: trunk build -M --release --dist ../docs/simulation --public-url 'https://tommy-gilligan.github.io/rp235x-nokia-3310/simulation'
      working-directory: web
    - run: cargo doc
      working-directory: shared
    - run: mv target/doc docs/
    - name: Upload static files as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
