name: Rust linting and formatting

on:
  push:
  pull_request:

env:
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  stable:
    name: Rust
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy,rustfmt
          targets: thumbv8m.main-none-eabihf
      - run: cargo clippy --no-deps
        working-directory: rp
      - run: cargo clippy --no-deps
        working-directory: web
      - run: cargo clippy --no-deps
        working-directory: shared
      - run: cargo test
        working-directory: shared
      - run: cargo clippy --no-deps
        working-directory: snake
      - run: cargo test
        working-directory: snake
      - run: cargo clippy --no-deps
        working-directory: keyboard
      - run: cargo test
        working-directory: keyboard
      - run: cargo clippy --no-deps
        working-directory: ringtones
      - run: cargo clippy --no-deps
        working-directory: clock
      - run: cargo test
        working-directory: clock
      - run: cargo clippy --no-deps
        working-directory: hardware_test
      - run: cargo test
        working-directory: hardware_test
      - run: cargo test
        working-directory: ringtones
        #      - run: cargo clippy --no-deps
        #        working-directory: rtttl
      - run: cargo test
        working-directory: rtttl
      - run: cargo fmt --check


keyboard
ringtones
rp
rtttl
shared
snake
web
